DetectorID: fy2015_version_b
PreTriggerSamples: 20
PostTriggerSamples: 500
SamplesInEventPacket: 520
DownSamplingFactorForSavedWaveform: 1
ChannelEnable: [no,no,yes,yes]
TriggerThresholds: [810, 810, 520, 520]
TriggerCloseThresholds: [800, 800, 510, 510]
