DetectorID: fy2015_version_a
PreTriggerSamples: 10
PostTriggerSamples: 500
SamplesInEventPacket: 510 
DownSamplingFactorForSavedWaveform: 1
ChannelEnable: [no, no, no, true]
TriggerThresholds: [810, 810, 810, 530]
TriggerCloseThresholds: [800, 800, 800, 570]
