PreTriggerSamples: 10
PostTriggerSamples: 500
SamplesInEventPacket: 10
DownSamplingFactorForSavedWaveform: 4
ChannelEnable: [true, true, true, true]
TriggerThresholds: [800, 800, 800, 530]
TriggerCloseThresholds: [800, 800, 800, 570]
