#!/bin/sh

sudo apt-get update
sudo apt-get install -y binutils
sudo apt-get install -y build-essential
sudo apt-get install -y chromium
sudo apt-get install -y cmake
sudo apt-get install -y curl
sudo apt-get install -y curl-dev
sudo apt-get install -y dpkg-dev
sudo apt-get install -y fswebcam
sudo apt-get install -y git
sudo apt-get install -y i2c-tools
sudo apt-get install -y imagemagick
sudo apt-get install -y libboost1.50-all
sudo apt-get install -y libbz2-dev
sudo apt-get install -y libcfitsio3-dev
sudo apt-get install -y libcurl4-openssl-dev
sudo apt-get install -y libexpat-dev
sudo apt-get install -y libjpeg8-dev
sudo apt-get install -y libncurses-dev
sudo apt-get install -y libssl-dev
sudo apt-get install -y libx11-dev
sudo apt-get install -y libxerces-c-dev
sudo apt-get install -y libxext-dev
sudo apt-get install -y libxft-dev
sudo apt-get install -y libxpm-dev
sudo apt-get install -y libyaml-cpp-dev
sudo apt-get install -y libzmq-dev
sudo apt-get install -y libzmq3-dev
sudo apt-get install -y make
sudo apt-get install -y python-dev
sudo apt-get install -y python-imaging
sudo apt-get install -y python-smbus
sudo apt-get install -y python-zmq
sudo apt-get install -y rails
sudo apt-get install -y ruby
sudo apt-get install -y ruby-dev
sudo apt-get install -y ruby-ffi
sudo apt-get install -y subversion
sudo apt-get install -y supervisor
sudo apt-get install -y swig
sudo apt-get install -y texinfo
sudo apt-get install -y wget
sudo apt-get install -y wicd-curses
sudo apt-get install -y zlib1g-dev
sudo apt-get install -y zsh
