all:
	@echo "1. Build external libraries by executing 'make prepare_external_libs'"
	@echo "2. Execute 'make -f Makefile.mac -j4' (Mac) or 'make -f Makefile.pi -j4' (Raspberry Pi)"
	@echo "   Alternatively, 'make mac' and 'make pi' are also available." 

mac:
	make -f Makefile.mac -j4

pi:
	make -f Makefile.pi -j4
